boundary:
    - {id: 25, name: inlet,  profile_space: uniform, profile_time: wave,    dir: 0, value: 1} 
    - {id: 25, name: inlet,  profile_space: uniform, profile_time: uniform, dir: 1, value: 0}
    - {id: 27, name: wall,   profile_space: uniform, profile_time: uniform, dir: 0, value: 0}
    - {id: 27, name: wall,   profile_space: uniform, profile_time: uniform, dir: 1, value: 0}
    - {id: 28, name: wall,   profile_space: uniform, profile_time: uniform, dir: 0, value: 0}
    - {id: 28, name: wall,   profile_space: uniform, profile_time: uniform, dir: 1, value: 0}
    - {id: 26, name: outlet, profile_space: uniform, profile_time: uniform, dir: 2, value: 0}

waveform: 
    a: 0.1
    b: 0.2
    T: 0.3

time:
  dt: 0.001
  t_end: 1.2

